# Generated by Django 5.0.7 on 2026-09-19 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'ordering': ['-creado']},
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='fecha',
        ),
        migrations.AddField(
            model_name='permiso',
            name='comentario_rechazo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='permiso',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 19, 15, 22, 4, 562303, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permiso',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='permisos/'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='motivo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='tipo',
            field=models.CharField(choices=[('personal', 'Permiso personal'), ('oficio', 'Oficio de comisión')], max_length=15),
        ),
    ]
