# Generated by Django 5.0.7 on 2026-09-19 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_permiso_options_remove_permiso_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='conductor',
            name='unidad_asignada',
            field=models.ForeignKey(blank=True, help_text='Unidad asignada de forma fija a este conductor (distinto del Servicio del día).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductores_asignados', to='core.unidad'),
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('retraso', 'Retraso'), ('falla_mecanica', 'Falla mecánica'), ('accidente_menor', 'Accidente menor'), ('queja_cliente', 'Queja de cliente')], max_length=20)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='core.conductor')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='core.unidad')),
            ],
            options={
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha'],
            },
        ),
    ]
