# Generated by Django 5.0.7 on 2026-09-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conductor_telefono_conductor_unidad_asignada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='conductor_actual',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='unidad',
            name='domicilio_conductor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='unidad',
            name='kilometraje',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unidad',
            name='ruta_actual',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
