# Generated by Django 5.0.7 on 2026-09-22 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_unidad_conductor_actual_unidad_domicilio_conductor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], default='preventivo', max_length=15)),
                ('kms', models.CharField(blank=True, default='', max_length=30)),
                ('tecnologia', models.CharField(blank=True, default='', max_length=50)),
                ('tipo_servicio_texto', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('conductor', models.CharField(max_length=150)),
                ('categorias', models.JSONField(default=list)),
                ('conformidad_conductor', models.CharField(blank=True, default='', max_length=150)),
                ('firma_jefe_mantenimiento', models.CharField(blank=True, default='', max_length=150)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_conductor', to='core.unidad')),
            ],
            options={
                'verbose_name': 'Reporte del Conductor',
                'verbose_name_plural': 'Reportes del Conductor',
                'ordering': ['-creado'],
            },
        ),
    ]
