# Generated by Django 5.0.7 on 2026-09-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reporteconductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraauditoria',
            name='modulo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
