# Generated by Django 5.0.7 on 2026-09-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bitacoraauditoria_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='domicilio',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
