# Generated by Django 5.0.7 on 2026-09-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usuario_domicilio_usuario_foto_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='preferencias_notificaciones',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
