# Generated by Django 5.0.7 on 2026-09-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sesionactiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='aforo',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='aforos/'),
        ),
    ]
