# Generated by Django 5.0.7 on 2026-09-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aforo_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallazgoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_deteccion', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hallazgo de auditoría',
                'verbose_name_plural': 'Hallazgos de auditoría',
                'ordering': ['-fecha_limite'],
            },
        ),
    ]
